---
# tasks file for roles/python_venv
- name: Ensure pip, python, virtualenv installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: present
    update_cache: yes
  become: true

- name: Instantiate virtual environment
  ansible.builtin.command:
    cmd: virtualenv {{ venv_dir }}
    creates: "{{ venv_dir }}"
  become: true

- name: Set Python and pip paths as facts
  ansible.builtin.set_fact:
    ansible_venv_path: "{{ venv_dir}}"
    ansible_python_path: "{{ venv_dir }}/bin/python"
    ansible_pip_path: "{{ venv_dir }}/bin/pip"