---
namespace: "hoodnoah"
name: "homelab_provisioning"
description: "Ansible roles for tasks common across hosts for provisioning my homelab"
version: "2.0.0"
readme: "README.md"
authors:
  - "Noah Hood <hood.noah@icloud.com>"
license:
  - "MIT"
tags:
  - "hoodnoah"
  - "python"
  - "venv"
  - "virtualenv"
  - "docker"
  - "docker_compose"
repository: "https://github.com/hoodnoah/homelab_provisioning"
build_ignore:
  - "venv"
  - ".gitignore"
  - ".github"
  - "*.tar.gz"
  - "*.json"
  - test_inventory
  - test_playbook.yaml
dependencies:
  "community.docker": "3.6.0-b1"