---
namespace: "hoodnoah"
name: "homelab_provisioning"
description: "Ansible roles for tasks common across hosts for provisioning my homelab"
version: "1.0.0"
readme: "README.md"
authors:
  - "Noah Hood <hood.noah@icloud.com>"
license:
  - "MIT"
tags:
  - "hoodnoah"
  - "python"
  - "venv"
  - "virtualenv"
  - "docker"
  - "docker-compose"
repository: "https://github.com/hoodnoah/homelab_provisioning"