galaxy_info:
  author: Noah Hood
  description: A role for setting the time zone on a host

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions:
        - "jammy"

  galaxy_tags:
    - timezone

dependencies: []
